/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.analysis;

import compilador.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTSuplementar(TSuplementar node);
    void caseTComentario(TComentario node);
    void caseTInicioExecucao(TInicioExecucao node);
    void caseTInicio(TInicio node);
    void caseTFim(TFim node);
    void caseTTipoCaractere(TTipoCaractere node);
    void caseTTipoNumero(TTipoNumero node);
    void caseTTipoBooleano(TTipoBooleano node);
    void caseTTipoVetor(TTipoVetor node);
    void caseTTipoVazio(TTipoVazio node);
    void caseTSe(TSe node);
    void caseTSenao(TSenao node);
    void caseTPara(TPara node);
    void caseTParaCada(TParaCada node);
    void caseTEnquanto(TEnquanto node);
    void caseTRetorne(TRetorne node);
    void caseTPonto(TPonto node);
    void caseTDoisPontos(TDoisPontos node);
    void caseTVirgula(TVirgula node);
    void caseTPontoVirgula(TPontoVirgula node);
    void caseTBarraReta(TBarraReta node);
    void caseTAbreParentese(TAbreParentese node);
    void caseTFechaParentese(TFechaParentese node);
    void caseTAbreColchete(TAbreColchete node);
    void caseTFechaColchete(TFechaColchete node);
    void caseTSoma(TSoma node);
    void caseTMenos(TMenos node);
    void caseTDivisao(TDivisao node);
    void caseTMultiplicacao(TMultiplicacao node);
    void caseTIgual(TIgual node);
    void caseTMaior(TMaior node);
    void caseTMenor(TMenor node);
    void caseTAtribuicao(TAtribuicao node);
    void caseTMaiorIgual(TMaiorIgual node);
    void caseTMenorIgual(TMenorIgual node);
    void caseTE(TE node);
    void caseTOu(TOu node);
    void caseTNao(TNao node);
    void caseTLer(TLer node);
    void caseTExibir(TExibir node);
    void caseTCaractere(TCaractere node);
    void caseTTexto(TTexto node);
    void caseTNumero(TNumero node);
    void caseTBooleano(TBooleano node);
    void caseTId(TId node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
