/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AAuxidAuxId extends PAuxId
{
    private TId _id_;
    private TDoisPontos _doisPontos_;

    public AAuxidAuxId()
    {
        // Constructor
    }

    public AAuxidAuxId(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TDoisPontos _doisPontos_)
    {
        // Constructor
        setId(_id_);

        setDoisPontos(_doisPontos_);

    }

    @Override
    public Object clone()
    {
        return new AAuxidAuxId(
            cloneNode(this._id_),
            cloneNode(this._doisPontos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAuxidAuxId(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TDoisPontos getDoisPontos()
    {
        return this._doisPontos_;
    }

    public void setDoisPontos(TDoisPontos node)
    {
        if(this._doisPontos_ != null)
        {
            this._doisPontos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doisPontos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._doisPontos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._doisPontos_ == child)
        {
            this._doisPontos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._doisPontos_ == oldChild)
        {
            setDoisPontos((TDoisPontos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
