/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AAuxatribAuxListaAtrib extends PAuxListaAtrib
{
    private PListaAtrib _listaAtrib_;
    private TPontoVirgula _pontoVirgula_;

    public AAuxatribAuxListaAtrib()
    {
        // Constructor
    }

    public AAuxatribAuxListaAtrib(
        @SuppressWarnings("hiding") PListaAtrib _listaAtrib_,
        @SuppressWarnings("hiding") TPontoVirgula _pontoVirgula_)
    {
        // Constructor
        setListaAtrib(_listaAtrib_);

        setPontoVirgula(_pontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AAuxatribAuxListaAtrib(
            cloneNode(this._listaAtrib_),
            cloneNode(this._pontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAuxatribAuxListaAtrib(this);
    }

    public PListaAtrib getListaAtrib()
    {
        return this._listaAtrib_;
    }

    public void setListaAtrib(PListaAtrib node)
    {
        if(this._listaAtrib_ != null)
        {
            this._listaAtrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaAtrib_ = node;
    }

    public TPontoVirgula getPontoVirgula()
    {
        return this._pontoVirgula_;
    }

    public void setPontoVirgula(TPontoVirgula node)
    {
        if(this._pontoVirgula_ != null)
        {
            this._pontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaAtrib_)
            + toString(this._pontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaAtrib_ == child)
        {
            this._listaAtrib_ = null;
            return;
        }

        if(this._pontoVirgula_ == child)
        {
            this._pontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaAtrib_ == oldChild)
        {
            setListaAtrib((PListaAtrib) newChild);
            return;
        }

        if(this._pontoVirgula_ == oldChild)
        {
            setPontoVirgula((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
