/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoBloco extends PBloco
{
    private TInicio _inicio_;
    private PDecVarMais _decVarMais_;
    private PComMais _comMais_;
    private TFim _fim_;

    public ABlocoBloco()
    {
        // Constructor
    }

    public ABlocoBloco(
        @SuppressWarnings("hiding") TInicio _inicio_,
        @SuppressWarnings("hiding") PDecVarMais _decVarMais_,
        @SuppressWarnings("hiding") PComMais _comMais_,
        @SuppressWarnings("hiding") TFim _fim_)
    {
        // Constructor
        setInicio(_inicio_);

        setDecVarMais(_decVarMais_);

        setComMais(_comMais_);

        setFim(_fim_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoBloco(
            cloneNode(this._inicio_),
            cloneNode(this._decVarMais_),
            cloneNode(this._comMais_),
            cloneNode(this._fim_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoBloco(this);
    }

    public TInicio getInicio()
    {
        return this._inicio_;
    }

    public void setInicio(TInicio node)
    {
        if(this._inicio_ != null)
        {
            this._inicio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicio_ = node;
    }

    public PDecVarMais getDecVarMais()
    {
        return this._decVarMais_;
    }

    public void setDecVarMais(PDecVarMais node)
    {
        if(this._decVarMais_ != null)
        {
            this._decVarMais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decVarMais_ = node;
    }

    public PComMais getComMais()
    {
        return this._comMais_;
    }

    public void setComMais(PComMais node)
    {
        if(this._comMais_ != null)
        {
            this._comMais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comMais_ = node;
    }

    public TFim getFim()
    {
        return this._fim_;
    }

    public void setFim(TFim node)
    {
        if(this._fim_ != null)
        {
            this._fim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inicio_)
            + toString(this._decVarMais_)
            + toString(this._comMais_)
            + toString(this._fim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inicio_ == child)
        {
            this._inicio_ = null;
            return;
        }

        if(this._decVarMais_ == child)
        {
            this._decVarMais_ = null;
            return;
        }

        if(this._comMais_ == child)
        {
            this._comMais_ = null;
            return;
        }

        if(this._fim_ == child)
        {
            this._fim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inicio_ == oldChild)
        {
            setInicio((TInicio) newChild);
            return;
        }

        if(this._decVarMais_ == oldChild)
        {
            setDecVarMais((PDecVarMais) newChild);
            return;
        }

        if(this._comMais_ == oldChild)
        {
            setComMais((PComMais) newChild);
            return;
        }

        if(this._fim_ == oldChild)
        {
            setFim((TFim) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
