/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AComparacaoExprComparacao extends PExprComparacao
{
    private PExprComparacao _exprComparacao_;
    private POpComp _opComp_;
    private PExprLogica _exprLogica_;

    public AComparacaoExprComparacao()
    {
        // Constructor
    }

    public AComparacaoExprComparacao(
        @SuppressWarnings("hiding") PExprComparacao _exprComparacao_,
        @SuppressWarnings("hiding") POpComp _opComp_,
        @SuppressWarnings("hiding") PExprLogica _exprLogica_)
    {
        // Constructor
        setExprComparacao(_exprComparacao_);

        setOpComp(_opComp_);

        setExprLogica(_exprLogica_);

    }

    @Override
    public Object clone()
    {
        return new AComparacaoExprComparacao(
            cloneNode(this._exprComparacao_),
            cloneNode(this._opComp_),
            cloneNode(this._exprLogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComparacaoExprComparacao(this);
    }

    public PExprComparacao getExprComparacao()
    {
        return this._exprComparacao_;
    }

    public void setExprComparacao(PExprComparacao node)
    {
        if(this._exprComparacao_ != null)
        {
            this._exprComparacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprComparacao_ = node;
    }

    public POpComp getOpComp()
    {
        return this._opComp_;
    }

    public void setOpComp(POpComp node)
    {
        if(this._opComp_ != null)
        {
            this._opComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opComp_ = node;
    }

    public PExprLogica getExprLogica()
    {
        return this._exprLogica_;
    }

    public void setExprLogica(PExprLogica node)
    {
        if(this._exprLogica_ != null)
        {
            this._exprLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprLogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprComparacao_)
            + toString(this._opComp_)
            + toString(this._exprLogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprComparacao_ == child)
        {
            this._exprComparacao_ = null;
            return;
        }

        if(this._opComp_ == child)
        {
            this._opComp_ = null;
            return;
        }

        if(this._exprLogica_ == child)
        {
            this._exprLogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprComparacao_ == oldChild)
        {
            setExprComparacao((PExprComparacao) newChild);
            return;
        }

        if(this._opComp_ == oldChild)
        {
            setOpComp((POpComp) newChild);
            return;
        }

        if(this._exprLogica_ == oldChild)
        {
            setExprLogica((PExprLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
