/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AComparacaoExprRelacional extends PExprRelacional
{
    private PExprRelacional _exprRelacional_;
    private POpComp _opComp_;
    private PExprLogica _exprLogica_;

    public AComparacaoExprRelacional()
    {
        // Constructor
    }

    public AComparacaoExprRelacional(
        @SuppressWarnings("hiding") PExprRelacional _exprRelacional_,
        @SuppressWarnings("hiding") POpComp _opComp_,
        @SuppressWarnings("hiding") PExprLogica _exprLogica_)
    {
        // Constructor
        setExprRelacional(_exprRelacional_);

        setOpComp(_opComp_);

        setExprLogica(_exprLogica_);

    }

    @Override
    public Object clone()
    {
        return new AComparacaoExprRelacional(
            cloneNode(this._exprRelacional_),
            cloneNode(this._opComp_),
            cloneNode(this._exprLogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComparacaoExprRelacional(this);
    }

    public PExprRelacional getExprRelacional()
    {
        return this._exprRelacional_;
    }

    public void setExprRelacional(PExprRelacional node)
    {
        if(this._exprRelacional_ != null)
        {
            this._exprRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprRelacional_ = node;
    }

    public POpComp getOpComp()
    {
        return this._opComp_;
    }

    public void setOpComp(POpComp node)
    {
        if(this._opComp_ != null)
        {
            this._opComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opComp_ = node;
    }

    public PExprLogica getExprLogica()
    {
        return this._exprLogica_;
    }

    public void setExprLogica(PExprLogica node)
    {
        if(this._exprLogica_ != null)
        {
            this._exprLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprLogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprRelacional_)
            + toString(this._opComp_)
            + toString(this._exprLogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprRelacional_ == child)
        {
            this._exprRelacional_ = null;
            return;
        }

        if(this._opComp_ == child)
        {
            this._opComp_ = null;
            return;
        }

        if(this._exprLogica_ == child)
        {
            this._exprLogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprRelacional_ == oldChild)
        {
            setExprRelacional((PExprRelacional) newChild);
            return;
        }

        if(this._opComp_ == oldChild)
        {
            setOpComp((POpComp) newChild);
            return;
        }

        if(this._exprLogica_ == oldChild)
        {
            setExprLogica((PExprLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
