/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AComparaFator extends PFator
{
    private PExprComparacao _exprComparacao_;

    public AComparaFator()
    {
        // Constructor
    }

    public AComparaFator(
        @SuppressWarnings("hiding") PExprComparacao _exprComparacao_)
    {
        // Constructor
        setExprComparacao(_exprComparacao_);

    }

    @Override
    public Object clone()
    {
        return new AComparaFator(
            cloneNode(this._exprComparacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComparaFator(this);
    }

    public PExprComparacao getExprComparacao()
    {
        return this._exprComparacao_;
    }

    public void setExprComparacao(PExprComparacao node)
    {
        if(this._exprComparacao_ != null)
        {
            this._exprComparacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprComparacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprComparacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprComparacao_ == child)
        {
            this._exprComparacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprComparacao_ == oldChild)
        {
            setExprComparacao((PExprComparacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
