/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ADivFator extends PFator
{
    private PFator _fator_;
    private TDivisao _divisao_;
    private PExprRelacional _exprRelacional_;

    public ADivFator()
    {
        // Constructor
    }

    public ADivFator(
        @SuppressWarnings("hiding") PFator _fator_,
        @SuppressWarnings("hiding") TDivisao _divisao_,
        @SuppressWarnings("hiding") PExprRelacional _exprRelacional_)
    {
        // Constructor
        setFator(_fator_);

        setDivisao(_divisao_);

        setExprRelacional(_exprRelacional_);

    }

    @Override
    public Object clone()
    {
        return new ADivFator(
            cloneNode(this._fator_),
            cloneNode(this._divisao_),
            cloneNode(this._exprRelacional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivFator(this);
    }

    public PFator getFator()
    {
        return this._fator_;
    }

    public void setFator(PFator node)
    {
        if(this._fator_ != null)
        {
            this._fator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fator_ = node;
    }

    public TDivisao getDivisao()
    {
        return this._divisao_;
    }

    public void setDivisao(TDivisao node)
    {
        if(this._divisao_ != null)
        {
            this._divisao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._divisao_ = node;
    }

    public PExprRelacional getExprRelacional()
    {
        return this._exprRelacional_;
    }

    public void setExprRelacional(PExprRelacional node)
    {
        if(this._exprRelacional_ != null)
        {
            this._exprRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprRelacional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fator_)
            + toString(this._divisao_)
            + toString(this._exprRelacional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fator_ == child)
        {
            this._fator_ = null;
            return;
        }

        if(this._divisao_ == child)
        {
            this._divisao_ = null;
            return;
        }

        if(this._exprRelacional_ == child)
        {
            this._exprRelacional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fator_ == oldChild)
        {
            setFator((PFator) newChild);
            return;
        }

        if(this._divisao_ == oldChild)
        {
            setDivisao((TDivisao) newChild);
            return;
        }

        if(this._exprRelacional_ == oldChild)
        {
            setExprRelacional((PExprRelacional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
