/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpressaomaisListaExpr extends PListaExpr
{
    private TBarraReta _barraReta_;
    private PExpr _expr_;

    public AExpressaomaisListaExpr()
    {
        // Constructor
    }

    public AExpressaomaisListaExpr(
        @SuppressWarnings("hiding") TBarraReta _barraReta_,
        @SuppressWarnings("hiding") PExpr _expr_)
    {
        // Constructor
        setBarraReta(_barraReta_);

        setExpr(_expr_);

    }

    @Override
    public Object clone()
    {
        return new AExpressaomaisListaExpr(
            cloneNode(this._barraReta_),
            cloneNode(this._expr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressaomaisListaExpr(this);
    }

    public TBarraReta getBarraReta()
    {
        return this._barraReta_;
    }

    public void setBarraReta(TBarraReta node)
    {
        if(this._barraReta_ != null)
        {
            this._barraReta_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._barraReta_ = node;
    }

    public PExpr getExpr()
    {
        return this._expr_;
    }

    public void setExpr(PExpr node)
    {
        if(this._expr_ != null)
        {
            this._expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._barraReta_)
            + toString(this._expr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._barraReta_ == child)
        {
            this._barraReta_ = null;
            return;
        }

        if(this._expr_ == child)
        {
            this._expr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._barraReta_ == oldChild)
        {
            setBarraReta((TBarraReta) newChild);
            return;
        }

        if(this._expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
