/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AInicioPrograma extends PPrograma
{
    private PDecVarMais _decVarMais_;

    public AInicioPrograma()
    {
        // Constructor
    }

    public AInicioPrograma(
        @SuppressWarnings("hiding") PDecVarMais _decVarMais_)
    {
        // Constructor
        setDecVarMais(_decVarMais_);

    }

    @Override
    public Object clone()
    {
        return new AInicioPrograma(
            cloneNode(this._decVarMais_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInicioPrograma(this);
    }

    public PDecVarMais getDecVarMais()
    {
        return this._decVarMais_;
    }

    public void setDecVarMais(PDecVarMais node)
    {
        if(this._decVarMais_ != null)
        {
            this._decVarMais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decVarMais_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decVarMais_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decVarMais_ == child)
        {
            this._decVarMais_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decVarMais_ == oldChild)
        {
            setDecVarMais((PDecVarMais) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
