/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ATiponumeroTipoBase extends PTipoBase
{
    private TTipoNumero _tipoNumero_;

    public ATiponumeroTipoBase()
    {
        // Constructor
    }

    public ATiponumeroTipoBase(
        @SuppressWarnings("hiding") TTipoNumero _tipoNumero_)
    {
        // Constructor
        setTipoNumero(_tipoNumero_);

    }

    @Override
    public Object clone()
    {
        return new ATiponumeroTipoBase(
            cloneNode(this._tipoNumero_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATiponumeroTipoBase(this);
    }

    public TTipoNumero getTipoNumero()
    {
        return this._tipoNumero_;
    }

    public void setTipoNumero(TTipoNumero node)
    {
        if(this._tipoNumero_ != null)
        {
            this._tipoNumero_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoNumero_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoNumero_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoNumero_ == child)
        {
            this._tipoNumero_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoNumero_ == oldChild)
        {
            setTipoNumero((TTipoNumero) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
