/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVarDecVarMais extends PDecVarMais
{
    private PDecVariavel _decVariavel_;

    public AVarDecVarMais()
    {
        // Constructor
    }

    public AVarDecVarMais(
        @SuppressWarnings("hiding") PDecVariavel _decVariavel_)
    {
        // Constructor
        setDecVariavel(_decVariavel_);

    }

    @Override
    public Object clone()
    {
        return new AVarDecVarMais(
            cloneNode(this._decVariavel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarDecVarMais(this);
    }

    public PDecVariavel getDecVariavel()
    {
        return this._decVariavel_;
    }

    public void setDecVariavel(PDecVariavel node)
    {
        if(this._decVariavel_ != null)
        {
            this._decVariavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decVariavel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decVariavel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decVariavel_ == child)
        {
            this._decVariavel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decVariavel_ == oldChild)
        {
            setDecVariavel((PDecVariavel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
