/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVetorTipo extends PTipo
{
    private TTipoVetor _tipoVetor_;
    private PTipoBase _tipoBase_;
    private PTipo _tipo_;

    public AVetorTipo()
    {
        // Constructor
    }

    public AVetorTipo(
        @SuppressWarnings("hiding") TTipoVetor _tipoVetor_,
        @SuppressWarnings("hiding") PTipoBase _tipoBase_,
        @SuppressWarnings("hiding") PTipo _tipo_)
    {
        // Constructor
        setTipoVetor(_tipoVetor_);

        setTipoBase(_tipoBase_);

        setTipo(_tipo_);

    }

    @Override
    public Object clone()
    {
        return new AVetorTipo(
            cloneNode(this._tipoVetor_),
            cloneNode(this._tipoBase_),
            cloneNode(this._tipo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVetorTipo(this);
    }

    public TTipoVetor getTipoVetor()
    {
        return this._tipoVetor_;
    }

    public void setTipoVetor(TTipoVetor node)
    {
        if(this._tipoVetor_ != null)
        {
            this._tipoVetor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoVetor_ = node;
    }

    public PTipoBase getTipoBase()
    {
        return this._tipoBase_;
    }

    public void setTipoBase(PTipoBase node)
    {
        if(this._tipoBase_ != null)
        {
            this._tipoBase_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoBase_ = node;
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoVetor_)
            + toString(this._tipoBase_)
            + toString(this._tipo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoVetor_ == child)
        {
            this._tipoVetor_ = null;
            return;
        }

        if(this._tipoBase_ == child)
        {
            this._tipoBase_ = null;
            return;
        }

        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoVetor_ == oldChild)
        {
            setTipoVetor((TTipoVetor) newChild);
            return;
        }

        if(this._tipoBase_ == oldChild)
        {
            setTipoBase((PTipoBase) newChild);
            return;
        }

        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
