/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AListaNomes extends PListaNomes
{
    private TId _id_;
    private final LinkedList<PMultiplosIds> _multiplosIds_ = new LinkedList<PMultiplosIds>();

    public AListaNomes()
    {
        // Constructor
    }

    public AListaNomes(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<?> _multiplosIds_)
    {
        // Constructor
        setId(_id_);

        setMultiplosIds(_multiplosIds_);

    }

    @Override
    public Object clone()
    {
        return new AListaNomes(
            cloneNode(this._id_),
            cloneList(this._multiplosIds_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaNomes(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PMultiplosIds> getMultiplosIds()
    {
        return this._multiplosIds_;
    }

    public void setMultiplosIds(List<?> list)
    {
        for(PMultiplosIds e : this._multiplosIds_)
        {
            e.parent(null);
        }
        this._multiplosIds_.clear();

        for(Object obj_e : list)
        {
            PMultiplosIds e = (PMultiplosIds) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._multiplosIds_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._multiplosIds_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._multiplosIds_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PMultiplosIds> i = this._multiplosIds_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMultiplosIds) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
