/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplosParametros extends PMultiplosParametros
{
    private TBarraReta _barraReta_;
    private PParametro _parametro_;

    public AMultiplosParametros()
    {
        // Constructor
    }

    public AMultiplosParametros(
        @SuppressWarnings("hiding") TBarraReta _barraReta_,
        @SuppressWarnings("hiding") PParametro _parametro_)
    {
        // Constructor
        setBarraReta(_barraReta_);

        setParametro(_parametro_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplosParametros(
            cloneNode(this._barraReta_),
            cloneNode(this._parametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplosParametros(this);
    }

    public TBarraReta getBarraReta()
    {
        return this._barraReta_;
    }

    public void setBarraReta(TBarraReta node)
    {
        if(this._barraReta_ != null)
        {
            this._barraReta_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._barraReta_ = node;
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._barraReta_)
            + toString(this._parametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._barraReta_ == child)
        {
            this._barraReta_ = null;
            return;
        }

        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._barraReta_ == oldChild)
        {
            setBarraReta((TBarraReta) newChild);
            return;
        }

        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
