/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplosExp extends PMultiplosExp
{
    private TBarraReta _barraReta_;
    private PExp _exp_;

    public AMultiplosExp()
    {
        // Constructor
    }

    public AMultiplosExp(
        @SuppressWarnings("hiding") TBarraReta _barraReta_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setBarraReta(_barraReta_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplosExp(
            cloneNode(this._barraReta_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplosExp(this);
    }

    public TBarraReta getBarraReta()
    {
        return this._barraReta_;
    }

    public void setBarraReta(TBarraReta node)
    {
        if(this._barraReta_ != null)
        {
            this._barraReta_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._barraReta_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._barraReta_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._barraReta_ == child)
        {
            this._barraReta_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._barraReta_ == oldChild)
        {
            setBarraReta((TBarraReta) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
