/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ANaoCasadoComando extends PComando
{
    private PNaoCasado _naoCasado_;

    public ANaoCasadoComando()
    {
        // Constructor
    }

    public ANaoCasadoComando(
        @SuppressWarnings("hiding") PNaoCasado _naoCasado_)
    {
        // Constructor
        setNaoCasado(_naoCasado_);

    }

    @Override
    public Object clone()
    {
        return new ANaoCasadoComando(
            cloneNode(this._naoCasado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANaoCasadoComando(this);
    }

    public PNaoCasado getNaoCasado()
    {
        return this._naoCasado_;
    }

    public void setNaoCasado(PNaoCasado node)
    {
        if(this._naoCasado_ != null)
        {
            this._naoCasado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._naoCasado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._naoCasado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._naoCasado_ == child)
        {
            this._naoCasado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._naoCasado_ == oldChild)
        {
            setNaoCasado((PNaoCasado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
