/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ANumeroExp extends PExp
{
    private PNumeroComSinal _numeroComSinal_;

    public ANumeroExp()
    {
        // Constructor
    }

    public ANumeroExp(
        @SuppressWarnings("hiding") PNumeroComSinal _numeroComSinal_)
    {
        // Constructor
        setNumeroComSinal(_numeroComSinal_);

    }

    @Override
    public Object clone()
    {
        return new ANumeroExp(
            cloneNode(this._numeroComSinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumeroExp(this);
    }

    public PNumeroComSinal getNumeroComSinal()
    {
        return this._numeroComSinal_;
    }

    public void setNumeroComSinal(PNumeroComSinal node)
    {
        if(this._numeroComSinal_ != null)
        {
            this._numeroComSinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numeroComSinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numeroComSinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numeroComSinal_ == child)
        {
            this._numeroComSinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numeroComSinal_ == oldChild)
        {
            setNumeroComSinal((PNumeroComSinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
