/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AParamParametros extends PParametros
{
    private PParametro _parametro_;
    private final LinkedList<PMultiplosParametros> _multiplosParametros_ = new LinkedList<PMultiplosParametros>();

    public AParamParametros()
    {
        // Constructor
    }

    public AParamParametros(
        @SuppressWarnings("hiding") PParametro _parametro_,
        @SuppressWarnings("hiding") List<?> _multiplosParametros_)
    {
        // Constructor
        setParametro(_parametro_);

        setMultiplosParametros(_multiplosParametros_);

    }

    @Override
    public Object clone()
    {
        return new AParamParametros(
            cloneNode(this._parametro_),
            cloneList(this._multiplosParametros_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParamParametros(this);
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    public LinkedList<PMultiplosParametros> getMultiplosParametros()
    {
        return this._multiplosParametros_;
    }

    public void setMultiplosParametros(List<?> list)
    {
        for(PMultiplosParametros e : this._multiplosParametros_)
        {
            e.parent(null);
        }
        this._multiplosParametros_.clear();

        for(Object obj_e : list)
        {
            PMultiplosParametros e = (PMultiplosParametros) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._multiplosParametros_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametro_)
            + toString(this._multiplosParametros_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        if(this._multiplosParametros_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        for(ListIterator<PMultiplosParametros> i = this._multiplosParametros_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMultiplosParametros) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
