/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVazioTipoRetorno extends PTipoRetorno
{
    private TTipoVazio _tipoVazio_;

    public AVazioTipoRetorno()
    {
        // Constructor
    }

    public AVazioTipoRetorno(
        @SuppressWarnings("hiding") TTipoVazio _tipoVazio_)
    {
        // Constructor
        setTipoVazio(_tipoVazio_);

    }

    @Override
    public Object clone()
    {
        return new AVazioTipoRetorno(
            cloneNode(this._tipoVazio_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVazioTipoRetorno(this);
    }

    public TTipoVazio getTipoVazio()
    {
        return this._tipoVazio_;
    }

    public void setTipoVazio(TTipoVazio node)
    {
        if(this._tipoVazio_ != null)
        {
            this._tipoVazio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoVazio_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoVazio_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoVazio_ == child)
        {
            this._tipoVazio_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoVazio_ == oldChild)
        {
            setTipoVazio((TTipoVazio) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
