/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVetorTipo extends PTipo
{
    private TTipoVetor _tipoVetor_;
    private PTipoBase _tipoBase_;
    private final LinkedList<PExpEntreColchetes> _expEntreColchetes_ = new LinkedList<PExpEntreColchetes>();

    public AVetorTipo()
    {
        // Constructor
    }

    public AVetorTipo(
        @SuppressWarnings("hiding") TTipoVetor _tipoVetor_,
        @SuppressWarnings("hiding") PTipoBase _tipoBase_,
        @SuppressWarnings("hiding") List<?> _expEntreColchetes_)
    {
        // Constructor
        setTipoVetor(_tipoVetor_);

        setTipoBase(_tipoBase_);

        setExpEntreColchetes(_expEntreColchetes_);

    }

    @Override
    public Object clone()
    {
        return new AVetorTipo(
            cloneNode(this._tipoVetor_),
            cloneNode(this._tipoBase_),
            cloneList(this._expEntreColchetes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVetorTipo(this);
    }

    public TTipoVetor getTipoVetor()
    {
        return this._tipoVetor_;
    }

    public void setTipoVetor(TTipoVetor node)
    {
        if(this._tipoVetor_ != null)
        {
            this._tipoVetor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoVetor_ = node;
    }

    public PTipoBase getTipoBase()
    {
        return this._tipoBase_;
    }

    public void setTipoBase(PTipoBase node)
    {
        if(this._tipoBase_ != null)
        {
            this._tipoBase_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoBase_ = node;
    }

    public LinkedList<PExpEntreColchetes> getExpEntreColchetes()
    {
        return this._expEntreColchetes_;
    }

    public void setExpEntreColchetes(List<?> list)
    {
        for(PExpEntreColchetes e : this._expEntreColchetes_)
        {
            e.parent(null);
        }
        this._expEntreColchetes_.clear();

        for(Object obj_e : list)
        {
            PExpEntreColchetes e = (PExpEntreColchetes) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expEntreColchetes_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoVetor_)
            + toString(this._tipoBase_)
            + toString(this._expEntreColchetes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoVetor_ == child)
        {
            this._tipoVetor_ = null;
            return;
        }

        if(this._tipoBase_ == child)
        {
            this._tipoBase_ = null;
            return;
        }

        if(this._expEntreColchetes_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoVetor_ == oldChild)
        {
            setTipoVetor((TTipoVetor) newChild);
            return;
        }

        if(this._tipoBase_ == oldChild)
        {
            setTipoBase((PTipoBase) newChild);
            return;
        }

        for(ListIterator<PExpEntreColchetes> i = this._expEntreColchetes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpEntreColchetes) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
